--- # Ansible playbook 
- name: MXNet build
  hosts: all
  gather_facts: no
  become: true
  become_user: "{{ user_name }}"
  tasks:
    - name: Copy MXNet build config cmake_options.yml
      copy:
        src: cmake_options.yml
        dest: "/home/{{ user_name }}/cmake_options.yml"

    - name: Check out latest mxnet source
      shell: |
        set -e
        git clone -q --recursive https://github.com/larroy/mxnet.git
        cp cmake_options.yml mxnet
      args:
        executable: /bin/bash
        chdir: "/home/{{ user_name }}"
        creates: "/home/{{ user_name }}/mxnet"

    - name: Build mxnet
      shell: |
        set -e
        cd mxnet
        ./dev_menu.py build >> build.log 2>&1
      args:
        executable: /bin/bash
        chdir: "/home/{{ user_name }}"
        creates: "/home/{{ user_name }}/mxnet/build/libmxnet.so"

    - name: Check out gluon-cv source
      shell: |
        set -e
        git clone -q --recursive https://github.com/larroy/gluon-cv.git
      args:
        executable: /bin/bash
        chdir: "/home/{{ user_name }}"
        creates: "/home/{{ user_name }}/gluon-cv"

    - name: Build gluon-cv
      shell: |
        set -e
        source mxnet/py3_venv/bin/activate
        pip install cython
        pip install pycocotools
        #pip3 install -e gluon-cv > /dev/null
        cd gluon-cv && python setup.py install --with-cython
      args:
        executable: /bin/bash
        chdir: "/home/{{ user_name }}"
        creates: "/home/{{ user_name }}/gluon-cv/gluoncv.egg-info"

    - name: Check out gluon-nlp source
      shell: |
        set -e
        git clone -q --recursive https://github.com/larroy/gluon-nlp.git
      args:
        executable: /bin/bash
        chdir: "/home/{{ user_name }}"
        creates: "/home/{{ user_name }}/gluon-nlp"

    - name: Build gluon-nlp
      shell: |
        set -e
        source mxnet/py3_venv/bin/activate
        pip3 install -e gluon-nlp > /dev/null
      args:
        executable: /bin/bash
        chdir: "/home/{{ user_name }}"
        creates: "/home/{{ user_name }}/gluon-nlp/src/gluonnlp.egg-info"



